language: python
python:
  - "3.6"
  
# Command to install dependencies.
install:
  - pip install -r requirements.txt
  - python -m nltk.downloader punkt
  - python -m nltk.downloader stopwords
  - pip install pytest
  - pip install pytest-cov
  - pip install python-coveralls
# Command to run tests.
script:
  - travis_wait 30 pytest --cov
#after_success:
  - coveralls
